### ISSUE TITLE
symbol not found in flat namespace '_npy_double_to_half'

### ISSUE THREAD

**Issue by alexlatif** [static-frame/arraykit#108]
https://github.com/static-frame/static-frame/issues/783

**Comment by flexatone** [comment]
This is the issue seen on Apple Silicon machines:
```
ImportError: dlopen(/Users/x/venv/lib/python3.11/site-packages/arraykit/_arraykit.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '_npy_double_to_half'
```

**Comment by flexatone** [comment]
This may be related to issues that others are having on M1/M2s using Python with compiled resources.

https://github.com/protocolbuffers/protobuf/issues/10571

**Comment by flexatone** [comment]
I have finally been able to configure my GitHub Action CI to build `arm64` wheels on Apple Silicon runners, which is what is needed to resolve this issue.
